config/routes.rb
Rails.application.routes.draw do
  get 'admin_page/category'
  post 'admin_page/category', to: 'admin_page#show_category'
  get 'admin_page/home'
  root 'categories#index'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users, :except => :index
  resources :categories
  get 'categories/new'
  resources :messages, :except => :index
  get '/signup', to: 'users#new'
  get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :messages, -> { order(created_at: :desc) }, dependent: :destroy
  validates :name, presence: true, length: {maximum: 100}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, length: {maximum: 50}
  validates :email, length: {maximum: 255}
  validates :subject, length: {maximum: 100}
  validates :text, presence: true, length: {maximum: 255}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :message, dependent: :destroy
  validates :name, presence: true, length: {maximum: 50}, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? 
      BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password::create(string, cost: cost)
  end

end

app/controllers/admin_page_controller.rb
class AdminPageController < ApplicationController
  before_action :admin_user
  def home
  end

  def category
    @categories = Category.paginate(page: params[:page])
  end

  def show_category
    @category = Category.find(params[:id])
    @messages = @category.messages.paginate(page: params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :admin_user, only: [:new, :create, :edit, :update, :destory]

  def index
    @categories = Category.paginate(page: params[:page])
  end

  def show
    @category = Category.find(params[:id])
    if logged_in?
      @message = Message.new({category_id: params[:id], user_id: current_user.id})
      @messages = @category.messages.where(user_id: current_user.id).or(@category.messages.where(visibility: true)).paginate(page: params[:page])
    else
      @message = nil
      @messages = @category.messages.where(visibility: true).paginate(page: params[:page])
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Created Category!"
      redirect_to admin_page_category_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category updated"
      redirect_to admin_page_category_path
    else
      render 'edit'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to admin_page_category_path
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :posted_user, only: [:edit, :update]
  before_action :logged_in_user, only: [:new, :create]

  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:success] = "Created Message!"
      redirect_to @message.category
    else
      render 'new'
    end
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    @message.toggle(:visibility)
    if @message.update(visiblity_params)
      flash[:success] = "Message updated"
      redirect_to @message.category
    else
      render 'edit'
    end
  end

  def destroy
    Message.find(params[:id]).destroy
    flash[:success] = "Message deleted"
    redirect_to messages_url
  end

  private
    def message_params
      params.require(:message).permit(:user_id, :category_id, :name, :email, :subject, :text)
    end

    def visiblity_params
      params.permit(:visibility)
    end

    def posted_user
      message = Message.find(params[:id])
      redirect_to root_url unless current_user == message.user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_back_or root_url
    else
      flash.now[:danger] = 'Invalid name/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @messages = Message.where(user: @user).paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Simple Board!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation, :admin)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/admin_page_helper.rb
module AdminPageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "Simple Board"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user && user == current_user
  end

  # 記憶したURL（もしくはデフォルト値）にリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def admin_user
    redirect_to(root_url) unless current_user && current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_page/_admin_category.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <%= link_to category.name, category %>
  <% if admin_page ||= false %>
    <span class="badge bg-primary rounded-pill"><%= category.messages.count %></span>
  <% end %>
</li>

app/views/admin_page/category.html.erb
<h1>AdminPage#category</h1>

<% if logged_in? && current_user.admin? %>
  <%= link_to 'Create Category', new_category_path, class: "btn btn-primary" %> 
<% end %>

<ul class="list-group">
 <%= render :partial => "categories/category", :collection => @categories, :locals => {admin_page: true} %> 
</ul>
<%= will_paginate @categories %>

app/views/admin_page/home.html.erb
<h1>AdminPage</h1>

<ul>
  <li>
    <%= link_to "Category", admin_page_category_path %>
  </li>
</ul>

app/views/admin_page/show_category.html.erb
<%= provide(:title, @category.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="category_info">
      <h1 class="name">
        <%= @category.name %>
      </h1>
      <h4 class="count">Messages (<%= @messages.count %>)</h4>
      <div>
        <%= link_to 'edit', edit_category_path(@category), method: :get, class: 'btn btn-sm btn-default' %>
        <%= link_to "delete", @category, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-sm btn-danger'  %>
      </div>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @messages.any? %>
      <ol class="list-group">
        <%= render :partial => "layouts/message", :collection => @messages, :locals => {admin_page: true} %>
      </ol>
      <%= will_paginate @messages %>
    <% end %>
  </div>
</div>

app/views/categories/_category.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <%= link_to category.name, category %>
  <% if logged_in? && current_user.admin? %>
    <span class="badge bg-primary rounded-pill"><%= category.messages.count %></span>
    <%= link_to 'edit', edit_category_path(category), method: :get, class: 'btn btn-sm btn-default' %>
    <%= link_to "delete", category, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-sm btn-danger'  %>
  <% end %>
</li>

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %> 
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/categories/_message.html.erb
<li>
  <%= link_to message.subject, message_url(id: message.id) %>
  <%= message.text %>
  <%= message.created_at %>
  <%= message.name %>
  <%= message.visibility %>
  <%= message.user.id %>
  <%= message.id %>
  <%= message.category.id %>
  <% if current_user == message.user %>
  | <%= link_to message.visibility ? "非表示にする" : "表示する", message, method: :patch, data: { confirm: "表示を変更しますか?" } %>
  <% end %> 
</li>

app/views/categories/edit.html.erb
<% provide(:title, 'Edit Category') %> 
<% provide(:button_text, 'Save changes') %>
<h1>Update category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/index.html.erb
<% provide(:title, 'Edit Category') %> 

<h1>Category List</h1>

<ul class="list-group">
  <%= render @categories %>
</ul>
<%= will_paginate @categories %>

app/views/categories/new.html.erb
<% provide(:title, 'Sign up') %> 
<% provide(:button_text, 'Create') %>

<h1>Create category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/categories/show.html.erb
<%= provide(:title, @category.name) %>
<%= provide(:button_text, "Post") %>
<div class="row">
  <section class="category_info">
    <h1>
      <%= @category.name %>
    </h1>
  </section>
  <div>
    <% if @messages.any? %>
      <h3>Messages (<%= @messages.count %>)</h3>
      <ol class="list-group">
        <%= render :partial => "layouts/message", :collection => @messages %>
      </ol>
      <%= will_paginate @messages %>
    <% end %>
  </div>

  <section>
    <h3>Post Message:</h3>
    <% if logged_in? %>
      <%= render :partial => "messages/form", locals: {category_id: @category.id, user_id: current_user.id} %>
    <% else %>
      <div id="error_explanation">
        <div class="alert alert-danger">
          You need to log in to post.
        <%= link_to "Log in", login_path %>
        </div>
      </div>
    <% end %>
  </section>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <%
=begin%>
 <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org">News</a></li> 
<%
=end%>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "SimpleBoard", root_path, id: "logo" %> 
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <% if logged_in? %>
        <% if current_user.admin? %>
         <li><%= link_to "Admin", admin_page_home_path %></li> 
       <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= current_user.name %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Posts", user_path(current_user) %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li> 
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li> 
      <% end %> 
    </ul>
  </nav>
  </div>
</header>

app/views/layouts/_message.html.erb
<li class="list-group-item message<%= ' message-hidden' if !message.visibility %>">
    <div class="header">
      <%= message.subject %>
      <small><%= message.created_at %></small>
    </div>
    <p class="mb-1"><%= message.text %></p>
    <div class="footer">
      <p>
        <small><%= message.name %></small>
        <small><%= message.email %></small>
      </p>
    <% if current_user == message.user || admin_page ||= false %>
    <%= link_to message.visibility ? "非表示" : "表示する", message, method: :patch, class: "btn btn-default" %>
    <% end %> 
</li>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>  

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapp</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: @message, local: true, url: messages_path) do |f| %>
 <%= render 'shared/error_messages', object: f.object %> 
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :subject %>
  <%= f.text_field :subject, class: "form-control" %>

  <%= f.label :text %>
  <%= f.text_field :text, class: "form-control" %>

 <%= f.hidden_field :category_id, class: "form-check-label" %> 
 <%= f.hidden_field :user_id, class: "form-control" %> 

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/messages/edit.html.erb
<%
=begin%>
 <% provide(:title, 'Edit Message') %> 
<%
=end%>
<% provide(:button_text, 'Save changes') %>
<h1>Update message</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>


<%
=begin%>
 <%= link_to 'edit', edit_message_path(@message), method: :get %> 
<%
=end%>
<%
=begin%>
 <%= link_to 'create', new_message_path %> 
<%
=end%>
<ul class="list-group">
  <%= render @messages %>
</ul>

app/views/messages/new.html.erb
<%
=begin%>
 <% provide(:title, 'Sign up') %> 
<%
=end%>
<% provide(:button_text, 'Create') %>

<h1>Create message</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/messages/show.html.erb
<%
=begin%>
 <%= provide(:title, @message.subject) %> 
<%
=end%>
<div class="row">
  <aside class="col-md-4">
    <section class="message_info">
      <h1>
        <%= @message.name %>
      </h1>
        <%= link_to 'edit', edit_message_path(@message), method: :get %>
    </section>
  </aside>
  <%
=begin%>
 <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div> 
<%
=end%>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <% if @user.admin? %>
    <%= f.label :admin %>
    <%= f.check_box :admin, class: "form-checkbox" %>
  <% end %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li class="list-group-item">
  <%= link_to user.name, user %>
   <% if current_user.admin? && !current_user?(user) %> 
    | 
    <%= link_to "edit", edit_user_path(user), method: :get %>
    <% if !current_user?(user) %>
      <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
    <% end %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:button_text, 'Users List') %>

<h1>Users#index</h1>
<ul class="list-group-item">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:button_text, 'Create User') %>

<h1>Users#new</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<h1><%= @user.name %></h1>

<div class="row">
  <% if @messages.any? %>
    <h3>Messages (<%= @messages.count %>)</h3>
    <ol class="messages">
      <%= render :partial => "layouts/message", collection: @messages %>
    </ol>
    <%= will_paginate @messages %> 
  <% end %> 
</div>